# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MariaGwyn
email: mariagwyn@gmail.com
name:  Maria Gwyn McDowell
description: >- # this means to ignore newlines until "baseurl:"
  Theology | Ethics | Liberation | Jesus
author: Maria Gwyn McDowell
author-image: /assets/images/authorpicture.jpg
copyright:     Copyright (c) 2022 | Maria Gwyn McDowell | All rights reserved
image-localpath: /assets/images/
image-baseurl: https://s3-us-west-2.amazonaws.com/mariagwyn-media/images/
image: hero-default.jpg # the default hero image for posts/pages
resume-pdf: /assets/documents/McDowell-Resume-Ekklesia_web.pdf
cv-pdf: /assets/documents/McDowell-CV.pdf

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mariagwyn.com" # the base hostname & protocol for your site, e.g. http://example.com
email:        mariagwyn@gmail.com
ga_id:        G-CDREMEBBR5

# Social Media
github:           mariagwyn
facebook:         mariagwyn
linkedin:   maria-mcdowell-29593218
soundcloud:       mariagwyn
youtube:          mariagwyn
twitter: mariagwyn
social:
  name: Maria Gwyn McDowell
  links:
    - https://twitter.com/mariagwyn
    - https://www.facebook.com/mariagwyn
    - https://www.linkedin.com/in/maria-mcdowell-29593218
    - https://github.com/mariagwyn

# RSS Settings
rss_path: /feed
rss_name: index.xml
rss_post_limit: 10
twitter_rss: /twitter

# Podcast General Settings
# ------------------------------------------------------------------------

# The homepage of your podcast
podcast_url: http://www.mariagwyn.com/vocedeiprofundis
podcast_album_art: /assets/images/Maria_McDowell-2017.jpg
podcast_title: Voce DeiProfundis
podcast_owner: Maria Gwyn McDowell
podcast_email: mariagwyn@gmail.com
podcast_category: Religion
podcast_subcategory_one: Christianity
podcast_subcategory_two: Ethics
podcast_explicit: "no"
podcast_author: Maria Gwyn McDowell
podcast_description: Sermons, lectures, and conversations on Theology, Ethics, and Practice. Presented by Maria Gwyn McDowell.
podcast_summary: Sermons, lectures, and conversations on Theology, Ethics, and Practice. Presented by Maria Gwyn McDowell.
podcast_subtitle: Sermons, lectures, and conversations on Theology, Ethics, and Practice. Presented by Maria Gwyn McDowell.
podcast_album_art: /assets/images/Maria_McDowell-2017.jpg
audio_basurl: https://mariagwyn-media.s3.us-west-2.amazonaws.com/sermons/audio/
video_basurl: https://mariagwyn-media.s3.us-west-2.amazonaws.com/sermons/video/

defaults:
  -
    scope:
       path: ""
    values:
      author: "Maria Gwyn McDowell"
  - scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image: hero-default.jpg
      show_sidebar: true
      post-listlong: false

# Build settings
# theme: mgm-bulma-jekyll
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
