# Site settings
title: Maria Gwyn McDowell
description: > # this means to ignore newlines until "baseurl:"
  Maria Gwyn McDowell is a scholar with a penchant for ministry, a theologian with an inclination for practice.  She is feminist, a student of liberation theology, Eastern Orthodoxy, and at her occassional best, a lover of God and all that God has created.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mariagwyn.com" # the base hostname & protocol for your site
twitter: mariagwyn
github:  mariagwyn
google: mariagwyn

# Build settings
source: _source
destination: public
markdown: kramdown
# Markdown Processors
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: :expanded
  # nested
  # expanded
  # compact
  # compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Maria Gwyn McDowell"
  -
    scope:
      path: "articles"
    values:
      layout: "article" # overrides previous default layout
      author: "Mr. Hyde"
