browsersync:
  notify: true
  open:   false
  port:   9002
  server:
    basedir: "public/"
  xip:    true

clean:
  # The jekyll build dir
  - "public"

copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks
  assets:
    # all files below the assets dir
    - "assets/**/*"
    # exclusions:
    - "!assets/sourceimgs{,/**/*}"             # BuildImages
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
    - "!assets/vendor{,/**}"         # vendor dir
  dist: "public/assets/"
  notification: "Running Copy"

javascript:
  dest:
    jekyllRoot: "assets/js/"
    buildDir: "public/assets/js/"
  # filename to output
  filename: "all.js"
  notification: "Running JavaScript"
  # Paths to JavaScript libraries, which are combined into one file
  src:
    # Libraries requried by Foundation
    - "node_modules/jquery/dist/jquery.js"
#    - "node_modules/what-input/what-input.js"

# FOUNDATION FILES HERE
    # Paths to your own project code are here
    # All the files in this list and in the js dir are concatenated into all.js
    - "!assets/js/all.js"
    - "assets/js/*.js"

jekyll:
  notification: "Running jekyll"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "public/assets/css/"
  notification: "Running Sass"
  src: "assets/scss/*.scss"

lint:
  src:
    - assets/scss/*.*
    - assets/scss/*/*.*

images:
  dest:
    jekyllRoot: "assets/images/"
    buildDir: "public/assets/images/"
  notification: "Optimizing Images"
  src:
    - "assets/img/*.jpg"
    - "assets/img/*.*"
    - "assets/img/*/*.*"
    - "assets/img/*/*/*.*"

watch:
  media:
    - "assets/img/**/*"
    - "assets/video/**/*"
  javascript: "assets/js/all.js"
  sass: "assets/scss/**/*.scss"
  pages:
    - "*.{md,html,yml,xml}"
    - "{_data,_includes,_layouts,_pages,_posts,blog}/**/*.{md,html,yml,xml}"
    - "!public/**/*.*"
    - "!assets/**/*.*"
